{% set name = "qonsole" %}
{% set version = "3.1.0" %}

package:
  name: qonsole
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/q/qonsole/qonsole-{{ version }}.tar.gz
  sha256: 4cb4a1f38f47e0f8f11b4fb871eac992609cc43115278b363b1ce26984019879

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - qtpy >=2.4.3,<3
    - jedi >=0.19.2,<0.20
    - pygments >=2.20.0,<3
    - ipython_pygments_lexers >=1.1.1,<2

test:
  imports:
    - qonsole
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - pyside6

about:
  home: https://github.com/jacobwilliams/qonsole
  summary: Light-weight python interpreter, easy to embed into Qt applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jacobwilliams
